//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}auditParent" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="modStore" type="{http://www.w3.org/2001/XMLSchema}string" default="FULL" />
 *       &lt;attribute name="relationTargetAuditMode" type="{http://www.w3.org/2001/XMLSchema}string" default="AUDITED" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "auditParent" })
@XmlRootElement(name = "audited")
public class Audited {

	protected List<AuditParent> auditParent;
	@XmlAttribute
	protected String modStore;
	@XmlAttribute
	protected String relationTargetAuditMode;

	/**
	 * Gets the value of the auditParent property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the auditParent property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAuditParent().add( newItem );
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link AuditParent }
	 * 
	 * 
	 */
	public List<AuditParent> getAuditParent() {
		if ( auditParent == null ) {
			auditParent = new ArrayList<AuditParent>();
		}
		return this.auditParent;
	}

	/**
	 * Gets the value of the modStore property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getModStore() {
		if ( modStore == null ) {
			return "FULL";
		}
		else {
			return modStore;
		}
	}

	/**
	 * Sets the value of the modStore property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModStore(String value) {
		this.modStore = value;
	}

	/**
	 * Gets the value of the relationTargetAuditMode property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getRelationTargetAuditMode() {
		if ( relationTargetAuditMode == null ) {
			return "AUDITED";
		}
		else {
			return relationTargetAuditMode;
		}
	}

	/**
	 * Sets the value of the relationTargetAuditMode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRelationTargetAuditMode(String value) {
		this.relationTargetAuditMode = value;
	}

}
