//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}auditJoinTable" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isAudited" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "auditJoinTable" })
@XmlRootElement(name = "auditOverride")
public class AuditOverride {

	protected AuditJoinTable auditJoinTable;
	@XmlAttribute
	protected String name;
	@XmlAttribute
	protected Boolean isAudited;

	/**
	 * Gets the value of the auditJoinTable property.
	 * 
	 * @return
	 *         possible object is {@link AuditJoinTable }
	 * 
	 */
	public AuditJoinTable getAuditJoinTable() {
		return auditJoinTable;
	}

	/**
	 * Sets the value of the auditJoinTable property.
	 * 
	 * @param value
	 *            allowed object is {@link AuditJoinTable }
	 * 
	 */
	public void setAuditJoinTable(AuditJoinTable value) {
		this.auditJoinTable = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the isAudited property.
	 * 
	 * @return
	 *         possible object is {@link Boolean }
	 * 
	 */
	public boolean isIsAudited() {
		if ( isAudited == null ) {
			return true;
		}
		else {
			return isAudited;
		}
	}

	/**
	 * Sets the value of the isAudited property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIsAudited(Boolean value) {
		this.isAudited = value;
	}

}
