//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}joinColumn" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="schema" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="catalog" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "joinColumn" })
@XmlRootElement(name = "auditJoinTable")
public class AuditJoinTable {

	protected List<JoinColumn> joinColumn;
	@XmlAttribute
	protected String name;
	@XmlAttribute
	protected String schema;
	@XmlAttribute
	protected String catalog;

	/**
	 * Gets the value of the joinColumn property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the joinColumn property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getJoinColumn().add( newItem );
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link JoinColumn }
	 * 
	 * 
	 */
	public List<JoinColumn> getJoinColumn() {
		if ( joinColumn == null ) {
			joinColumn = new ArrayList<JoinColumn>();
		}
		return this.joinColumn;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getName() {
		if ( name == null ) {
			return "";
		}
		else {
			return name;
		}
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the schema property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getSchema() {
		if ( schema == null ) {
			return "";
		}
		else {
			return schema;
		}
	}

	/**
	 * Sets the value of the schema property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSchema(String value) {
		this.schema = value;
	}

	/**
	 * Gets the value of the catalog property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getCatalog() {
		if ( catalog == null ) {
			return "";
		}
		else {
			return catalog;
		}
	}

	/**
	 * Sets the value of the catalog property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCatalog(String value) {
		this.catalog = value;
	}

}
