//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="mappedBy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="positionMappedBy" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "auditMappedBy")
public class AuditMappedBy {

	@XmlAttribute
	protected String mappedBy;
	@XmlAttribute
	protected String positionMappedBy;

	/**
	 * Gets the value of the mappedBy property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getMappedBy() {
		return mappedBy;
	}

	/**
	 * Sets the value of the mappedBy property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMappedBy(String value) {
		this.mappedBy = value;
	}

	/**
	 * Gets the value of the positionMappedBy property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getPositionMappedBy() {
		if ( positionMappedBy == null ) {
			return "";
		}
		else {
			return positionMappedBy;
		}
	}

	/**
	 * Sets the value of the positionMappedBy property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPositionMappedBy(String value) {
		this.positionMappedBy = value;
	}

}
