//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Envers configuration for a persistence class.
 * 
 * 
 * <p>
 * Java class for ClazzType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClazzType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}audited" minOccurs="0"/>
 *         &lt;element ref="{}auditTable" minOccurs="0"/>
 *         &lt;element ref="{}revisionEntity" minOccurs="0"/>
 *         &lt;element ref="{}secondaryAuditTable" minOccurs="0"/>
 *         &lt;element ref="{}secondaryAuditTables" minOccurs="0"/>
 *         &lt;element name="property" type="{}PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="component" type="{}ComponentType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClazzType", propOrder = { "audited", "auditTable", "revisionEntity", "secondaryAuditTable",
		"secondaryAuditTables", "property", "component" })
public class ClazzType {

	protected Audited audited;
	protected AuditTable auditTable;
	protected RevisionEntity revisionEntity;
	protected SecondaryAuditTable secondaryAuditTable;
	protected SecondaryAuditTables secondaryAuditTables;
	protected List<PropertyType> property;
	protected List<ComponentType> component;
	@XmlAttribute(required = true)
	protected String name;
	@XmlAttribute
	protected String parent;

	/**
	 * Gets the value of the audited property.
	 * 
	 * @return
	 *         possible object is {@link Audited }
	 * 
	 */
	public Audited getAudited() {
		return audited;
	}

	/**
	 * Sets the value of the audited property.
	 * 
	 * @param value
	 *            allowed object is {@link Audited }
	 * 
	 */
	public void setAudited(Audited value) {
		this.audited = value;
	}

	/**
	 * Gets the value of the auditTable property.
	 * 
	 * @return
	 *         possible object is {@link AuditTable }
	 * 
	 */
	public AuditTable getAuditTable() {
		return auditTable;
	}

	/**
	 * Sets the value of the auditTable property.
	 * 
	 * @param value
	 *            allowed object is {@link AuditTable }
	 * 
	 */
	public void setAuditTable(AuditTable value) {
		this.auditTable = value;
	}

	/**
	 * Gets the value of the revisionEntity property.
	 * 
	 * @return
	 *         possible object is {@link RevisionEntity }
	 * 
	 */
	public RevisionEntity getRevisionEntity() {
		return revisionEntity;
	}

	/**
	 * Sets the value of the revisionEntity property.
	 * 
	 * @param value
	 *            allowed object is {@link RevisionEntity }
	 * 
	 */
	public void setRevisionEntity(RevisionEntity value) {
		this.revisionEntity = value;
	}

	/**
	 * Gets the value of the secondaryAuditTable property.
	 * 
	 * @return
	 *         possible object is {@link SecondaryAuditTable }
	 * 
	 */
	public SecondaryAuditTable getSecondaryAuditTable() {
		return secondaryAuditTable;
	}

	/**
	 * Sets the value of the secondaryAuditTable property.
	 * 
	 * @param value
	 *            allowed object is {@link SecondaryAuditTable }
	 * 
	 */
	public void setSecondaryAuditTable(SecondaryAuditTable value) {
		this.secondaryAuditTable = value;
	}

	/**
	 * Gets the value of the secondaryAuditTables property.
	 * 
	 * @return
	 *         possible object is {@link SecondaryAuditTables }
	 * 
	 */
	public SecondaryAuditTables getSecondaryAuditTables() {
		return secondaryAuditTables;
	}

	/**
	 * Sets the value of the secondaryAuditTables property.
	 * 
	 * @param value
	 *            allowed object is {@link SecondaryAuditTables }
	 * 
	 */
	public void setSecondaryAuditTables(SecondaryAuditTables value) {
		this.secondaryAuditTables = value;
	}

	/**
	 * Gets the value of the property property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the property property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProperty().add( newItem );
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link PropertyType }
	 * 
	 * 
	 */
	public List<PropertyType> getProperty() {
		if ( property == null ) {
			property = new ArrayList<PropertyType>();
		}
		return this.property;
	}

	/**
	 * Gets the value of the component property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the component property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getComponent().add( newItem );
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ComponentType }
	 * 
	 * 
	 */
	public List<ComponentType> getComponent() {
		if ( component == null ) {
			component = new ArrayList<ComponentType>();
		}
		return this.component;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the parent property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getParent() {
		return parent;
	}

	/**
	 * Sets the value of the parent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setParent(String value) {
		this.parent = value;
	}

}
