//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * This Element represents the hibernate 'component' element (also known under the term embedded value)
 * 
 * 
 * <p>
 * Java class for ComponentType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="property" type="{}PropertyType"/>
 *         &lt;element name="entity" type="{}ClazzType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentType", propOrder = { "property", "entity" })
public class ComponentType {

	@XmlElement(required = true)
	protected PropertyType property;
	@XmlElement(required = true)
	protected ClazzType entity;

	/**
	 * Gets the value of the property property.
	 * 
	 * @return
	 *         possible object is {@link PropertyType }
	 * 
	 */
	public PropertyType getProperty() {
		return property;
	}

	/**
	 * Sets the value of the property property.
	 * 
	 * @param value
	 *            allowed object is {@link PropertyType }
	 * 
	 */
	public void setProperty(PropertyType value) {
		this.property = value;
	}

	/**
	 * Gets the value of the entity property.
	 * 
	 * @return
	 *         possible object is {@link ClazzType }
	 * 
	 */
	public ClazzType getEntity() {
		return entity;
	}

	/**
	 * Sets the value of the entity property.
	 * 
	 * @param value
	 *            allowed object is {@link ClazzType }
	 * 
	 */
	public void setEntity(ClazzType value) {
		this.entity = value;
	}

}
