//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="columnDefinition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="insertable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nullable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="referencedColumnName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="table" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="updatable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "joinColumn")
public class JoinColumn {

	@XmlAttribute
	protected String columnDefinition;
	@XmlAttribute
	protected Boolean insertable;
	@XmlAttribute
	protected String name;
	@XmlAttribute
	protected Boolean nullable;
	@XmlAttribute
	protected String referencedColumnName;
	@XmlAttribute
	protected String table;
	@XmlAttribute
	protected Boolean unique;
	@XmlAttribute
	protected Boolean updatable;

	/**
	 * Gets the value of the columnDefinition property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getColumnDefinition() {
		return columnDefinition;
	}

	/**
	 * Sets the value of the columnDefinition property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColumnDefinition(String value) {
		this.columnDefinition = value;
	}

	/**
	 * Gets the value of the insertable property.
	 * 
	 * @return
	 *         possible object is {@link Boolean }
	 * 
	 */
	public Boolean isInsertable() {
		return insertable;
	}

	/**
	 * Sets the value of the insertable property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setInsertable(Boolean value) {
		this.insertable = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the nullable property.
	 * 
	 * @return
	 *         possible object is {@link Boolean }
	 * 
	 */
	public Boolean isNullable() {
		return nullable;
	}

	/**
	 * Sets the value of the nullable property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setNullable(Boolean value) {
		this.nullable = value;
	}

	/**
	 * Gets the value of the referencedColumnName property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getReferencedColumnName() {
		return referencedColumnName;
	}

	/**
	 * Sets the value of the referencedColumnName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReferencedColumnName(String value) {
		this.referencedColumnName = value;
	}

	/**
	 * Gets the value of the table property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getTable() {
		return table;
	}

	/**
	 * Sets the value of the table property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTable(String value) {
		this.table = value;
	}

	/**
	 * Gets the value of the unique property.
	 * 
	 * @return
	 *         possible object is {@link Boolean }
	 * 
	 */
	public Boolean isUnique() {
		return unique;
	}

	/**
	 * Sets the value of the unique property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setUnique(Boolean value) {
		this.unique = value;
	}

	/**
	 * Gets the value of the updatable property.
	 * 
	 * @return
	 *         possible object is {@link Boolean }
	 * 
	 */
	public Boolean isUpdatable() {
		return updatable;
	}

	/**
	 * Sets the value of the updatable property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setUpdatable(Boolean value) {
		this.updatable = value;
	}

}
