//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.hibernate.envers.configuration.metadata.xml.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _RevisionNumber_QNAME = new QName( "", "revisionNumber" );
	private final static QName _EnversMapping_QNAME = new QName( "", "envers-mapping" );
	private final static QName _RevisionTimestamp_QNAME = new QName( "", "revisionTimestamp" );
	private final static QName _NotAudited_QNAME = new QName( "", "notAudited" );

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * org.hibernate.envers.configuration.metadata.xml.jaxb
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link RevisionEntity }
	 * 
	 */
	public RevisionEntity createRevisionEntity() {
		return new RevisionEntity();
	}

	/**
	 * Create an instance of {@link RevisionListener }
	 * 
	 */
	public RevisionListener createRevisionListener() {
		return new RevisionListener();
	}

	/**
	 * Create an instance of {@link AuditJoinTable }
	 * 
	 */
	public AuditJoinTable createAuditJoinTable() {
		return new AuditJoinTable();
	}

	/**
	 * Create an instance of {@link Version }
	 * 
	 */
	public Version createVersion() {
		return new Version();
	}

	/**
	 * Create an instance of {@link SecondaryAuditTable }
	 * 
	 */
	public SecondaryAuditTable createSecondaryAuditTable() {
		return new SecondaryAuditTable();
	}

	/**
	 * Create an instance of {@link ClazzType }
	 * 
	 */
	public ClazzType createClazzType() {
		return new ClazzType();
	}

	/**
	 * Create an instance of {@link AuditOverride }
	 * 
	 */
	public AuditOverride createAuditOverride() {
		return new AuditOverride();
	}

	/**
	 * Create an instance of {@link AuditParent }
	 * 
	 */
	public AuditParent createAuditParent() {
		return new AuditParent();
	}

	/**
	 * Create an instance of {@link Audited }
	 * 
	 */
	public Audited createAudited() {
		return new Audited();
	}

	/**
	 * Create an instance of {@link MapKey }
	 * 
	 */
	public MapKey createMapKey() {
		return new MapKey();
	}

	/**
	 * Create an instance of {@link AuditTable }
	 * 
	 */
	public AuditTable createAuditTable() {
		return new AuditTable();
	}

	/**
	 * Create an instance of {@link AuditOverrides }
	 * 
	 */
	public AuditOverrides createAuditOverrides() {
		return new AuditOverrides();
	}

	/**
	 * Create an instance of {@link EnversMappingType }
	 * 
	 */
	public EnversMappingType createEnversMappingType() {
		return new EnversMappingType();
	}

	/**
	 * Create an instance of {@link SecondaryAuditTables }
	 * 
	 */
	public SecondaryAuditTables createSecondaryAuditTables() {
		return new SecondaryAuditTables();
	}

	/**
	 * Create an instance of {@link JoinColumn }
	 * 
	 */
	public JoinColumn createJoinColumn() {
		return new JoinColumn();
	}

	/**
	 * Create an instance of {@link AuditMappedBy }
	 * 
	 */
	public AuditMappedBy createAuditMappedBy() {
		return new AuditMappedBy();
	}

	/**
	 * Create an instance of {@link PropertyType }
	 * 
	 */
	public PropertyType createPropertyType() {
		return new PropertyType();
	}

	/**
	 * Create an instance of {@link ComponentType }
	 * 
	 */
	public ComponentType createComponentType() {
		return new ComponentType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "revisionNumber")
	public JAXBElement<Object> createRevisionNumber(Object value) {
		return new JAXBElement<Object>( _RevisionNumber_QNAME, Object.class, null, value );
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link EnversMappingType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "envers-mapping")
	public JAXBElement<EnversMappingType> createEnversMapping(EnversMappingType value) {
		return new JAXBElement<EnversMappingType>( _EnversMapping_QNAME, EnversMappingType.class, null, value );
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "revisionTimestamp")
	public JAXBElement<Object> createRevisionTimestamp(Object value) {
		return new JAXBElement<Object>( _RevisionTimestamp_QNAME, Object.class, null, value );
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "notAudited")
	public JAXBElement<Object> createNotAudited(Object value) {
		return new JAXBElement<Object>( _NotAudited_QNAME, Object.class, null, value );
	}

}
