//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Envers configuration for a property of persistence class.
 * 
 * 
 * <p>
 * Java class for PropertyType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}audited" minOccurs="0"/>
 *         &lt;element ref="{}auditJoinTable" minOccurs="0"/>
 *         &lt;element ref="{}auditMappedBy" minOccurs="0"/>
 *         &lt;element ref="{}auditOverride" minOccurs="0"/>
 *         &lt;element ref="{}auditOverrides" minOccurs="0"/>
 *         &lt;element ref="{}notAudited" minOccurs="0"/>
 *         &lt;element ref="{}mapKey" minOccurs="0"/>
 *         &lt;element ref="{}version" minOccurs="0"/>
 *         &lt;element ref="{}revisionNumber" minOccurs="0"/>
 *         &lt;element ref="{}revisionTimestamp" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="propertyAccessorName" type="{http://www.w3.org/2001/XMLSchema}string" default="property" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyType", propOrder = { "audited", "auditJoinTable", "auditMappedBy", "auditOverride",
		"auditOverrides", "notAudited", "mapKey", "version", "revisionNumber", "revisionTimestamp" })
public class PropertyType {

	protected Audited audited;
	protected AuditJoinTable auditJoinTable;
	protected AuditMappedBy auditMappedBy;
	protected AuditOverride auditOverride;
	protected AuditOverrides auditOverrides;
	protected Object notAudited;
	protected MapKey mapKey;
	protected Version version;
	protected Object revisionNumber;
	protected Object revisionTimestamp;
	@XmlAttribute(required = true)
	protected String name;
	@XmlAttribute
	protected String propertyAccessorName;

	/**
	 * Gets the value of the audited property.
	 * 
	 * @return
	 *         possible object is {@link Audited }
	 * 
	 */
	public Audited getAudited() {
		return audited;
	}

	/**
	 * Sets the value of the audited property.
	 * 
	 * @param value
	 *            allowed object is {@link Audited }
	 * 
	 */
	public void setAudited(Audited value) {
		this.audited = value;
	}

	/**
	 * Gets the value of the auditJoinTable property.
	 * 
	 * @return
	 *         possible object is {@link AuditJoinTable }
	 * 
	 */
	public AuditJoinTable getAuditJoinTable() {
		return auditJoinTable;
	}

	/**
	 * Sets the value of the auditJoinTable property.
	 * 
	 * @param value
	 *            allowed object is {@link AuditJoinTable }
	 * 
	 */
	public void setAuditJoinTable(AuditJoinTable value) {
		this.auditJoinTable = value;
	}

	/**
	 * Gets the value of the auditMappedBy property.
	 * 
	 * @return
	 *         possible object is {@link AuditMappedBy }
	 * 
	 */
	public AuditMappedBy getAuditMappedBy() {
		return auditMappedBy;
	}

	/**
	 * Sets the value of the auditMappedBy property.
	 * 
	 * @param value
	 *            allowed object is {@link AuditMappedBy }
	 * 
	 */
	public void setAuditMappedBy(AuditMappedBy value) {
		this.auditMappedBy = value;
	}

	/**
	 * Gets the value of the auditOverride property.
	 * 
	 * @return
	 *         possible object is {@link AuditOverride }
	 * 
	 */
	public AuditOverride getAuditOverride() {
		return auditOverride;
	}

	/**
	 * Sets the value of the auditOverride property.
	 * 
	 * @param value
	 *            allowed object is {@link AuditOverride }
	 * 
	 */
	public void setAuditOverride(AuditOverride value) {
		this.auditOverride = value;
	}

	/**
	 * Gets the value of the auditOverrides property.
	 * 
	 * @return
	 *         possible object is {@link AuditOverrides }
	 * 
	 */
	public AuditOverrides getAuditOverrides() {
		return auditOverrides;
	}

	/**
	 * Sets the value of the auditOverrides property.
	 * 
	 * @param value
	 *            allowed object is {@link AuditOverrides }
	 * 
	 */
	public void setAuditOverrides(AuditOverrides value) {
		this.auditOverrides = value;
	}

	/**
	 * Gets the value of the notAudited property.
	 * 
	 * @return
	 *         possible object is {@link Object }
	 * 
	 */
	public Object getNotAudited() {
		return notAudited;
	}

	/**
	 * Sets the value of the notAudited property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setNotAudited(Object value) {
		this.notAudited = value;
	}

	/**
	 * Gets the value of the mapKey property.
	 * 
	 * @return
	 *         possible object is {@link MapKey }
	 * 
	 */
	public MapKey getMapKey() {
		return mapKey;
	}

	/**
	 * Sets the value of the mapKey property.
	 * 
	 * @param value
	 *            allowed object is {@link MapKey }
	 * 
	 */
	public void setMapKey(MapKey value) {
		this.mapKey = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return
	 *         possible object is {@link Version }
	 * 
	 */
	public Version getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link Version }
	 * 
	 */
	public void setVersion(Version value) {
		this.version = value;
	}

	/**
	 * Gets the value of the revisionNumber property.
	 * 
	 * @return
	 *         possible object is {@link Object }
	 * 
	 */
	public Object getRevisionNumber() {
		return revisionNumber;
	}

	/**
	 * Sets the value of the revisionNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setRevisionNumber(Object value) {
		this.revisionNumber = value;
	}

	/**
	 * Gets the value of the revisionTimestamp property.
	 * 
	 * @return
	 *         possible object is {@link Object }
	 * 
	 */
	public Object getRevisionTimestamp() {
		return revisionTimestamp;
	}

	/**
	 * Sets the value of the revisionTimestamp property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setRevisionTimestamp(Object value) {
		this.revisionTimestamp = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the propertyAccessorName property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getPropertyAccessorName() {
		if ( propertyAccessorName == null ) {
			return "property";
		}
		else {
			return propertyAccessorName;
		}
	}

	/**
	 * Sets the value of the propertyAccessorName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPropertyAccessorName(String value) {
		this.propertyAccessorName = value;
	}

}
