//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 01:04:46 PM MEZ 
//

package org.hibernate.envers.configuration.metadata.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="secondaryTableName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="secondaryAuditTableName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "secondaryAuditTable")
public class SecondaryAuditTable {

	@XmlAttribute(required = true)
	protected String secondaryTableName;
	@XmlAttribute(required = true)
	protected String secondaryAuditTableName;

	/**
	 * Gets the value of the secondaryTableName property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getSecondaryTableName() {
		return secondaryTableName;
	}

	/**
	 * Sets the value of the secondaryTableName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSecondaryTableName(String value) {
		this.secondaryTableName = value;
	}

	/**
	 * Gets the value of the secondaryAuditTableName property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getSecondaryAuditTableName() {
		return secondaryAuditTableName;
	}

	/**
	 * Sets the value of the secondaryAuditTableName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSecondaryAuditTableName(String value) {
		this.secondaryAuditTableName = value;
	}

}
